version: "3.8"

services:
  app:
    container_name: app-assoc
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - mongo-express
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: mongodb-assoc
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - "27017:27017"
    volumes:
      - .data/:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express
    container_name: mongo-express-assoc
    command: sh -c "sleep 9 && node app"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongodb:27017/?authSource=admin
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    restart: unless-stopped
